services:
  # 1. Web Server: Nginx (Reverse Proxy)
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    environment:
      - TZ=${TZ}
    container_name: nginx-proxy
    restart: always
    ports:
      - "7880:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - intogis

  # 2. WAS: Service Application (Tomcat)
  was:
    build:
      context: ./was
      dockerfile: Dockerfile
      args:
        - JDK_VERSION=${JDK_VERSION}
        - TOMCAT_VERSION=${TOMCAT_VERSION}
    container_name: was
    restart: always
    environment:
      - TZ=${TZ}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - intogis

# 컨테이너 간 통신을 위한 네트워크 정의
networks:
  intogis:
    driver: bridge
