services:
  # 1. Web Server: Nginx (Reverse Proxy)
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    environment:
      - TZ=${TZ}
    container_name: nginx-proxy
    restart: always
    ports:
      - "7880:80"
    networks:
      - intogis

  # 2. WAS: Service Application (Tomcat)
  was:
    build:
      context: ./was
      dockerfile: Dockerfile
      args:
        - JDK_VERSION=${JDK_VERSION}
        - TOMCAT_VERSION=${TOMCAT_VERSION}
    container_name: was
    restart: always
    environment:
      - TZ=${TZ}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - intogis

  # 3. GeoServer (Tomcat)
  geoserver-was:
    build:
      context: ./geoserver
      dockerfile: Dockerfile
      args:
        - ADMIN_USER=${GEOSERVER_ADMIN_USER}
        - ADMIN_PW=${GEOSERVER_ADMIN_PASSWORD}
    container_name: geoserver
    volumes:
      - "D:/workspace/02_work/02_greenblue/02_iho/91_volume/data:/opt/geoserver_data"
    environment:
      - TZ=${TZ}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
    restart: always
    networks:
      - intogis

# 컨테이너 간 통신을 위한 네트워크 정의
networks:
  intogis:
    driver: bridge
